name: Pull Request actions

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain:1-buster-slim-node16

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.17.1
      - name: Install dependencies
        run: pnpm install
      - name: Build JSII
        run: pnpm run build
      - name: Package JSII
        run: pnpm run package
